apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8081       # Service Port
      targetPort: 8081 # Container Port
  type: ClusterIP
